FROM summerwind/actions-runner:latest

SHELL ["/bin/bash", "-c"]
RUN sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh

WORKDIR /home/runner

RUN sudo apt update -y \
  && umask 0002 \
  && sudo apt install -y ca-certificates curl build-essential python3 g++ make python3-pip tar \
  && sudo curl -sL https://deb.nodesource.com/setup_16.x | sudo bash \
  && sudo apt install nodejs \
  && sudo npm install --location=global yarn

RUN sudo rm -rf /var/lib/apt/lists/*
