FROM ubuntu:latest
LABEL maintainer="Arthur Breton <abreton@siteed.net>"
ARG DEBIAN_FRONTEND=noninteractive

# default port value, can be overwritten
ARG PORT=1337
EXPOSE ${PORT}
# Replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
SHELL ["/bin/bash", "-c"]

ENV NODE_VERSION 16.16.0
ENV NVM_DIR /root/.nvm

USER root
# Set timezone otherwise image cannot build 
ENV TZ=Asia/Hong_Kong 
# Default dev packages
RUN apt-get update \
    && apt-get install -y curl vim \
    tzdata dumb-init wget openjdk-11-jdk-headless \
    hostname openssl netcat npm gcc build-essential net-tools tcpdump \
    iputils-ping lsb-release
# install extra repos
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg |  apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - \
    && echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list \
    curl -sL https://download.docker.com/linux/ubuntu/gpg | apt-key --keyring /usr/share/keyrings/docker-archive-keyring.gpg add - \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list \
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | apt-key --keyring /usr/share/keyrings/githubcli-archive-keyring.gpg add - \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list \
# update and install with new repos
RUN apt update \
    && apt install -y kubectl docker gh
# install nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install v$NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default \
    && npm install --location=global yarn pnpm

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH

CMD ["dumb-init", "nc", "-lkvv", "1337"]