FROM summerwind/actions-runner:latest

SHELL ["/bin/bash", "-c"]
RUN sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh

WORKDIR /home/runner

RUN sudo apt update -y \
  && umask 0002 \
  && sudo apt install -y ca-certificates curl build-essential \
  python3 gcc g++ make python3-pip tar lsb-release

# && curl -sL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key --keyring /usr/share/keyrings/docker-archive-keyring.gpg add - \
# && sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list \
RUN curl -sL https://deb.nodesource.com/setup_16.x | sudo bash \
  && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - \
  && curl https://baltocdn.com/helm/signing.asc | sudo apt-key --keyring /usr/share/keyrings/helm.gpg add - \
  && sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/cloud.google.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list \
  && sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm.list \
  && sudo apt update && sudo apt install -y nodejs kubectl helm \
  && sudo npm install --location=global yarn
