name: cicd

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ubuntu dev
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile.dev
          tags: deeeed/ubuntu-dev:latest
          platforms: linux/amd64,linux/arm64
    
      -
        name: Build and push github runner
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.runner
          push: true
          tags: deeeed/github-runner:latest
          platforms: linux/amd64,linux/arm64
